### PR TITLE
Update SharpPcap.csproj

### PR DESCRIPTION
**Pull request by FredeJ**
Remove LGPL3.0 license from Nuget. Update version to 6.3.0.

This should(?) create a new Nuget release as well, with the new license.

### CODE REVIEW

**Review by kayoub5 — APPROVED** [review]

**Comment by kayoub5** [comment]
@chmorgan could you double check the api key for nuget, CI is failing to upload a new version

**Comment by chmorgan** [comment]
Yep, I’ll check in this afternoon. Maybe it’s expired and I missed the
notice. Afaict there wasn’t a way to give you access to the account so you
could admin.

**Comment by chmorgan** [comment]
@kayoub5 updated secrets with new keys for all three repositories. Can you retry the build/package push?

**Comment by FredeJ** [comment]
The package was updated in the Nuget feed. Thanks a lot for the quick turnaround time :)

**Pull request merged**
