### PR TITLE
Change license to MIT

### PR DESCRIPTION
**Pull request by kayoub5**

### CODE REVIEW

**Comment by kayoub5** [comment]
@chmorgan could you review this? the coverage change seems to be sporadic due to https://github.com/dotpcap/sharppcap/blob/master/SharpPcap/WinDivert/WinDivertDevice.cs#L140-L154 block having the lines covered change depending on packet count/buffer size.

**Review by chmorgan — APPROVED** [review]
Overview of this looks good to me. Did you generate this by hand or some application that went through git history to update it?

**Comment by chmorgan** [comment]
@kayoub5 oh and no idea on the coverage issue. Surprised we'd get different results on different runs but maybe we have some tests that use random data without using a fixed random number seed.

**Comment by kayoub5** [comment]
> Overview of this looks good to me. Did you generate this by hand or some application that went through git history to update it?

For license I used a reuse-tool to inject the MIT header.
For copyright I checked files history manually, then used reuse-tool to make sure no file is missing copyright header (even added CI job for it), I didn't double check files that already had a copyright header.

**Pull request merged**
