### PR TITLE
Thread Safe Test

### PR DESCRIPTION
**Pull request by kayoub5**

### CODE REVIEW

**Comment by kayoub5** [comment]
@KoenPlasmansLS that's one weird test, the CI is lighting up like a christmas tree.

**Comment by KoenPlasmansLS** [comment]
To be honest, I wouldn't run this as a 'unit' test but I would run the code as a console application to see if it crashes after a while or not. You can run it on your laptop or a server and see if the application crashes after a while.
Maybe one more thing to mention is that we're using npcap-1.55 OEM.

**Comment by kayoub5** [comment]
@KoenPlasmansLS @chmorgan 
This PR changes reduces the chance of memory corruption, however it does not remove it 100%:

* Capture Device is NOT and was never a thread safe object, trying to call Open/Close on it from different threads will eventually lead to a heap corruption at the libpcap level, the reason is simple: pcap_t the underlying pcap handle itself is not thread safe, and the capture device does not offer ANY locking protection mechanisms.

* The observed crashes are NOT a bug in the sharppcap library, when non thread-safe object is mutated by multiple threads all kind of bad things happen, including memory access violations, this is not limited to sharppcap library.

Things that can be done from here:
* Make Capture Devices thread safe: a LOT of work, performance reduction, double work for each driver (WinDivert, TAP...).
* Reject the topic and document what methods are allowed to be called concurrently.
* Create a thread safe wrapper like [Stream.Synchronized](https://docs.microsoft.com/en-us/dotnet/api/system.io.stream.synchronized?view=net-5.0)
* Make Capture Devices immutable (remove Open and Close methods, see #338), so that a capture device can only be used once and it is activated at the moment of its creation. an immutable object is usually thread safe by nature.

**Review by chmorgan — APPROVED** [review]
I had to read about Task, I've never used it before. Changes look good but again I'm slightly clueless about the nuances here. I'd squash the changes to files together and put the test in its own commit but otherwise looks fine.

**Comment by kayoub5** [comment]
@chmorgan since the changes were approved, but the tests can not fully pass (see my above comment), I will move the code changes to a new PR and merge it, and keep only the tests here.

**Comment by kayoub5** [comment]
@KoenPlasmansLS should remove all the crashes related to `PacketCapture.GetPacket()` (in Windows at least), could you check if it solves your problem?

Linux crashes seems to be still present, but I will need to debug the crash dumps to see if it's `PacketCapture.GetPacket()` related or not.

**Comment by KoenPlasmansLS** [comment]
@kayoub5 Great, I'll test it out and come back to you!

**Comment by kayoub5** [comment]
Most of the changes of this PR were already merged in other smaller PRs, the only thing left is to make sure that the crash does not happen on Linux, that's outside the original request scope, so I will move remaining changes to their own PR.

**Pull request closed without merging**
