### PR TITLE
Use Codecov uploader where possible

### PR DESCRIPTION
**Pull request by kayoub5**

### CODE REVIEW

**Comment by kayoub5** [comment]
@chmorgan review

**Comment by kayoub5** [comment]
@chmorgan Code Review?

**Review by chmorgan — APPROVED** [review]
This looks ok but I don’t follow what this was fixing in terms of the ci build or if it’s a cleanup. Maybe @PhyxionNL would be a better reviewer?

**Comment by kayoub5** [comment]
> This looks ok but I don’t follow what this was fixing in terms of the ci build or if it’s a cleanup. Maybe @PhyxionNL would be a better reviewer?

Codecov Bash Uploader got deprecated, so switching to the new system
See https://about.codecov.io/blog/codecov-uploader-deprecation-plan/

**Pull request merged**
